import { index, integer, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

export const roleEnum = pgEnum("message_role", ["system", "user", "assistant"]);
export const statusEnum = pgEnum("generation_status", ["pending", "streaming", "completed", "failed", "cancelled"]);

export const users = pgTable("users", { id: uuid("id").primaryKey().defaultRandom(), name: text("name").notNull().default("Local user"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const providers = pgTable("providers", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), name: text("name").notNull(), baseUrl: text("base_url").notNull(), encryptedApiKey: text("encrypted_api_key").notNull(), customHeaders: text("custom_headers"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("providers_user_name_idx").on(t.userId, t.name)]);
export const models = pgTable("models", { id: uuid("id").primaryKey().defaultRandom(), providerId: uuid("provider_id").notNull().references(() => providers.id, { onDelete: "cascade" }), name: text("name").notNull(), displayName: text("display_name").notNull(), inputPricePerMillion: numeric("input_price_per_million", { precision: 12, scale: 6 }).notNull().default("0"), outputPricePerMillion: numeric("output_price_per_million", { precision: 12, scale: 6 }).notNull().default("0"), contextWindow: integer("context_window"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("models_provider_name_idx").on(t.providerId, t.name)]);
export const conversations = pgTable("conversations", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), title: text("title").notNull().default("New conversation"), modelId: uuid("model_id").references(() => models.id, { onDelete: "set null" }), systemPrompt: text("system_prompt"), temperature: numeric("temperature", { precision: 3, scale: 2 }).notNull().default("0.7"), topP: numeric("top_p", { precision: 3, scale: 2 }).notNull().default("1"), maxOutputTokens: integer("max_output_tokens").notNull().default(2048), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("conversations_user_updated_idx").on(t.userId, t.updatedAt)]);
export const messages = pgTable("messages", { id: uuid("id").primaryKey().defaultRandom(), conversationId: uuid("conversation_id").notNull().references(() => conversations.id, { onDelete: "cascade" }), role: roleEnum("role").notNull(), content: text("content").notNull(), parentId: uuid("parent_id"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("messages_conversation_created_idx").on(t.conversationId, t.createdAt)]);
export const generations = pgTable("generations", { id: uuid("id").primaryKey().defaultRandom(), conversationId: uuid("conversation_id").notNull().references(() => conversations.id, { onDelete: "cascade" }), messageId: uuid("message_id").references(() => messages.id, { onDelete: "set null" }), modelId: uuid("model_id").notNull().references(() => models.id, { onDelete: "restrict" }), status: statusEnum("status").notNull().default("pending"), errorCode: text("error_code"), startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp("completed_at", { withTimezone: true }) }, (t) => [index("generations_conversation_idx").on(t.conversationId)]);
export const usageRecords = pgTable("usage_records", { id: uuid("id").primaryKey().defaultRandom(), generationId: uuid("generation_id").notNull().unique().references(() => generations.id, { onDelete: "cascade" }), providerName: text("provider_name").notNull(), modelName: text("model_name").notNull(), inputTokens: integer("input_tokens"), outputTokens: integer("output_tokens"), totalTokens: integer("total_tokens"), durationMs: integer("duration_ms").notNull(), ttftMs: integer("ttft_ms"), tokensPerSecond: numeric("tokens_per_second", { precision: 10, scale: 2 }), estimatedInputCost: numeric("estimated_input_cost", { precision: 12, scale: 8 }), estimatedOutputCost: numeric("estimated_output_cost", { precision: 12, scale: 8 }), estimatedTotalCost: numeric("estimated_total_cost", { precision: 12, scale: 8 }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("usage_created_idx").on(t.createdAt), index("usage_model_idx").on(t.modelName)]);
