"use client";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { Copy, RefreshCw, Send, SlidersHorizontal, Square, Zap } from "./icons";
import { Markdown } from "./markdown";

type Msg={role:"user"|"assistant";content:string};
const starter:Msg[]=[{role:"user",content:"Review this approach for a streaming chat endpoint. What failure modes should I account for?"},{role:"assistant",content:"Treat the stream as a lifecycle, not just a response body. The important boundaries are **upstream connection**, **first token**, **incremental delivery**, and **final persistence**.\n\n```ts\nrequest.signal.addEventListener(\"abort\", () => upstream.abort());\n```\n\nPlan for client cancellation, provider timeouts, malformed SSE frames, partial output, and a disconnect after the model has finished but before your database write commits. Persist generation status independently from message content so interrupted work remains observable."}];
export function ChatWorkspace(){const [messages,setMessages]=useState<Msg[]>(starter);const [input,setInput]=useState("");const [streaming,setStreaming]=useState(false);const [advanced,setAdvanced]=useState(false);const controller=useRef<AbortController|null>(null);const bottom=useRef<HTMLDivElement>(null);
useEffect(()=>bottom.current?.scrollIntoView({behavior:streaming?"auto":"smooth"}),[messages,streaming]);
async function send(){const content=input.trim();if(!content||streaming)return;setInput("");setMessages(v=>[...v,{role:"user",content},{role:"assistant",content:""}]);setStreaming(true);controller.current=new AbortController();try{const r=await fetch("/api/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:content,modelId:localStorage.getItem("relay-model-id")??"00000000-0000-0000-0000-000000000000",temperature:.7,topP:1,maxOutputTokens:2048}),signal:controller.current.signal});if(!r.ok)throw new Error((await r.json().catch(()=>null))?.error??"Generation failed");const reader=r.body?.getReader();const decoder=new TextDecoder();if(!reader)throw new Error("Streaming is unavailable");while(true){const {done,value}=await reader.read();if(done)break;const chunk=decoder.decode(value,{stream:true});setMessages(v=>v.map((m,i)=>i===v.length-1?{...m,content:m.content+chunk}:m));}}catch(e){if((e as Error).name!=="AbortError") {toast.error((e as Error).message);setMessages(v=>v.map((m,i)=>i===v.length-1&&m.content===""?{...m,content:"The request could not be completed. Configure a provider and model in Settings, then retry."}:m));}}finally{setStreaming(false);controller.current=null;}}
return <main className="flex min-w-0 flex-1 flex-col bg-[var(--bg)]"><header className="flex h-16 shrink-0 items-center gap-3 border-b border-[var(--border)] px-4 md:px-6"><div><div className="text-sm font-medium">Streaming architecture review</div><div className="mt-0.5 text-xs text-[var(--muted)]">Saved just now</div></div><div className="ml-auto flex items-center gap-2"><button className="focus-ring flex h-9 items-center gap-2 rounded-md border border-[var(--border)] bg-[var(--panel)] px-3 text-sm hover:bg-[var(--raised)]"><span className="size-2 rounded-full bg-[var(--accent)]"/>Select a model</button><button onClick={()=>setAdvanced(!advanced)} aria-label="Generation settings" className="focus-ring rounded-md border border-[var(--border)] p-2 text-[var(--muted)] hover:bg-[var(--raised)] hover:text-white"><SlidersHorizontal size={17}/></button></div></header>
{advanced&&<div className="grid shrink-0 grid-cols-3 gap-5 border-b border-[var(--border)] bg-[var(--panel)] px-6 py-4 text-sm"><label>Temperature <input type="range" min="0" max="2" step=".1" defaultValue=".7" className="mt-2 w-full accent-[var(--accent)]"/></label><label>Max output tokens<input defaultValue="2048" className="mt-1.5 h-9 w-full rounded-md border border-[var(--border)] bg-black/20 px-3 outline-none"/></label><label>Top P<input defaultValue="1" className="mt-1.5 h-9 w-full rounded-md border border-[var(--border)] bg-black/20 px-3 outline-none"/></label></div>}
<div className="flex-1 overflow-y-auto"><div className="mx-auto max-w-3xl px-5 py-8 md:py-12">{messages.map((m,i)=><article key={i} className={`group mb-9 ${m.role==="user"?"ml-auto max-w-[85%]":""}`}>{m.role==="assistant"&&<div className="mb-3 flex items-center gap-2 text-xs font-medium text-[var(--muted)]"><span className="grid size-6 place-items-center rounded bg-[#20242b] text-[var(--accent)]"><Zap size={13}/></span>Assistant <span>·</span> qwen3-coder</div>}<div className={m.role==="user"?"rounded-lg border border-[#2a2e36] bg-[#171a20] px-4 py-3 leading-7":""}>{m.role==="assistant"?<Markdown content={m.content}/>:m.content}{streaming&&i===messages.length-1&&<span className="stream-dot ml-1 inline-block size-1.5 rounded-full bg-[var(--accent)]"/>}</div>{m.role==="assistant"&&m.content&&<div className="mt-3 flex items-center gap-1 text-[var(--muted)]"><button onClick={()=>navigator.clipboard.writeText(m.content)} aria-label="Copy message" className="focus-ring rounded p-1.5 hover:bg-white/5 hover:text-white"><Copy size={14}/></button><button aria-label="Regenerate" className="focus-ring rounded p-1.5 hover:bg-white/5 hover:text-white"><RefreshCw size={14}/></button>{i===messages.length-1&&!streaming&&<span className="ml-2 text-xs">1.8s · 327 tokens · ~$0.0012</span>}</div>}</article>)}<div ref={bottom}/></div></div>
<div className="shrink-0 border-t border-[var(--border)] bg-[var(--panel)] p-3 md:p-5"><div className="mx-auto max-w-3xl"><div className="rounded-xl border border-[#30343d] bg-[#111318] shadow-[0_12px_40px_rgba(0,0,0,.25)] focus-within:border-[#555b68]"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}} rows={2} placeholder="Ask anything…" className="min-h-20 w-full resize-none bg-transparent px-4 pt-4 text-[15px] leading-6 outline-none placeholder:text-[#606571]"/><div className="flex items-center px-3 pb-3"><span className="text-xs text-[#666c78]">↵ send · ⇧↵ new line</span>{streaming?<button onClick={()=>controller.current?.abort()} className="focus-ring ml-auto flex size-9 items-center justify-center rounded-md bg-white text-black"><Square size={14} fill="currentColor"/></button>:<button onClick={()=>void send()} disabled={!input.trim()} className="focus-ring ml-auto flex size-9 items-center justify-center rounded-md bg-[var(--accent)] text-black disabled:cursor-not-allowed disabled:opacity-30"><Send size={16}/></button>}</div></div><p className="mt-2 text-center text-xs text-[#555a65]">Responses may be inaccurate. Verify important information.</p></div></div></main>}
