import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { requireDb } from "@/db";
import { models, providers } from "@/db/schema";
import { decryptSecret } from "@/lib/crypto";
import { chatSchema } from "@/lib/security";
import { OpenAICompatibleProvider } from "@/providers/openai-compatible";

export const runtime = "nodejs";
export async function POST(request: Request){try{const length=Number(request.headers.get("content-length")??0);if(length>40_000)return NextResponse.json({error:"Request is too large"},{status:413});const body=chatSchema.parse(await request.json());const db=requireDb();const [row]=await db.select({model:models.name,baseUrl:providers.baseUrl,key:providers.encryptedApiKey,headers:providers.customHeaders}).from(models).innerJoin(providers,eq(models.providerId,providers.id)).where(eq(models.id,body.modelId)).limit(1);if(!row)return NextResponse.json({error:"Model not found. Add a provider and model in Settings."},{status:404});const adapter=new OpenAICompatibleProvider(row.baseUrl,decryptSecret(row.key),row.headers?JSON.parse(row.headers) as Record<string,string>:{});const upstream=await adapter.streamChat({model:row.model,messages:[...(body.systemPrompt?[{role:"system" as const,content:body.systemPrompt}]:[]),{role:"user",content:body.message}],temperature:body.temperature,topP:body.topP,maxOutputTokens:body.maxOutputTokens,signal:request.signal});if(!upstream.ok)return NextResponse.json({error:`Provider request failed (${upstream.status})`},{status:502});if(!upstream.body)throw new Error("Provider returned no stream");const decoder=new TextDecoder();const encoder=new TextEncoder();let carry="";const stream=new ReadableStream({async start(controller){const reader=upstream.body!.getReader();try{while(true){const {done,value}=await reader.read();if(done)break;carry+=decoder.decode(value,{stream:true});const lines=carry.split("\n");carry=lines.pop()??"";for(const line of lines){if(!line.startsWith("data: ")||line==="data: [DONE]")continue;try{const event=JSON.parse(line.slice(6)) as {choices?:Array<{delta?:{content?:string}}>};const text=event.choices?.[0]?.delta?.content;if(text)controller.enqueue(encoder.encode(text));}catch{}}}controller.close();}catch(error){controller.error(error);}}});return new Response(stream,{headers:{"Content-Type":"text/plain; charset=utf-8","Cache-Control":"no-cache, no-transform","X-Content-Type-Options":"nosniff"}});}catch(error){const message=error instanceof Error?error.message:"Invalid request";return NextResponse.json({error:message},{status:400});}}
